name: CI
on:
  - pull_request
jobs:
  build-lint-test:
    name: Build, Lint, and Test All Apps and Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Install Dependencies
        run: bun install
      - name: Run Prettier Lint
        run: bun run lint:prettier
      - name: Build All Apps and Packages
        run: bun run build
      - name: Run ESLint
        run: bun run lint:eslint
      - name: Run Tests
        run: bun test
